# Generated by Django 3.2.8 on 2021-10-15 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mails', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mail',
            name='mail_id',
        ),
        migrations.AddField(
            model_name='mail',
            name='mail_is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mail',
            name='mail_subject',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
